### ISSUE TITLE
Run flask not in debug mode

### ISSUE THREAD

**Issue by mharrend** [softdevteam/mattermost-github-integration#14]
Due to security reasons Flask should not run in debug mode:
```
app.run(host='0.0.0.0', port=port, debug=True)
```
Especially the possibility to execute arbitrary code in case of a failure is quite dangerous, have a look here:
http://flask.pocoo.org/docs/0.11/quickstart/#debug-mode

So, I would propose the simple solution to set
```
debug = False 
```
by default.

**Comment by ptersilie** [comment]
Good point. Fixed.
