### ISSUE TITLE
Wiki update are not implemented

### ISSUE THREAD

**Issue by valvin1** [softdevteam/mattermost-github-integration#19]
would it be possible to implement wiki update ?
now if I update it Github recieves HTTP 400 - Not implemented

**Comment by varod** [comment]
https://developer.github.com/v3/activity/events/types/#gollumevent

**Comment by varod** [comment]
i've implemented it, i will do a pull request

**Comment by ptersilie** [comment]
Great, thanks. Looking forward to the PR.
