### ISSUE TITLE
mattermost username

### ISSUE THREAD

**Issue by varod** [softdevteam/mattermost-github-integration#23]
I don't know if is in this part on mattermost side but username we specified in config.py is not used.

The username used is the one which has created the webhook. 

In my config.py I have : `USERNAME = "Github"` and in Mattermost it displays `mynickname (BOT)` 

we can so easily believe that i've sent this message.

**Comment by ptersilie** [comment]
Did you check if you have set *Enable webhooks and slash commands to override usernames* in your Notification settings?
