### ISSUE TITLE
How send error message from function node to template in node red to display in mattermost

### ISSUE THREAD

**Issue by chaitanya9249** [softdevteam/mattermost-github-integration#27]
Here is my node red flow:

![11](https://cloud.githubusercontent.com/assets/25222593/22284473/852d8116-e30d-11e6-938a-994a7a2ea992.jpg)

Here i am handling error.I am getting error message.But I am not understanding how to send that error message to "polistTemplate" to display in mattermost.

Here is my error handling code:

var dataMsg = msg.payload;
var msgVal;
var parseData = JSON.parse(dataMsg)
if (parseData.header.status === 400) {
    msgVal = parseData.header.message;
} else {
    msgVal = "Access Token Expired"
}
msg.payload = JSON.stringify(msgVal);
node.error(msgVal.toString(),msg);
node.send(msg);

Here i am sending msg to another node.It display in debug node well.But not in mattermost app.

Anyone please help me how to handle errors in node red and how to send them from one node to another node and how to prepare them in attachment format and display in **mattermost**

**Comment by ptersilie** [comment]
I really have no experience with node red and so I don't know how it works. However if you just want to send a message to Mattermost, you can do this like this:

```
def post(text, url, channel):
    data = {}
    data['text'] = text
    data['channel'] = channel

    headers = {'Content-Type': 'application/json'}
    r = requests.post(url, headers=headers, data=json.dumps(data), verify=False)

    if r.status_code is not requests.codes.ok:
        print 'Encountered error posting to Mattermost URL %s, status=%d, response_body=%s' % (url, r.status_code, r.json())
```

where `url` is your Mattermost integration URL, e.g. http://yourdomain.com/hooks/hookid, and `channel` is the channel you want to post the message to, e.g. 'townsquare'. The message is send as a json object to the Mattermost hook URL using Pythons `requests` library.

Hope that helps.

**Comment by chaitanya9249** [comment]
Thanks for the reply..
But I need a solution from node red..Any way thank you somuch

**Comment by chaitanya9249** [comment]
Here I am getting error because of invalid request parameters.Actually if we send any invalid parameter as an input it should throw an error message.But here I am getting error as JSON response.
Please any one help me How to handle error response while passing invalid parameters in from function node to http request node.

Here I am getting error response:

{"name":"StatusCodeError","statusCode":400,"message":"400 - \"{\\"header\\":{\\"status\\":400,\\"code\\":493,\\"message\\":\\"No xxxx found for the xxx.\\",\\"developerMessage\\":\\"We could not find any xxxx assigned to the xxxxx in database.\\"},\\"data\\":{\\"totalResponded\\":0,\\"totalResulted\\":0}}\"","error":"{\"header\":{\"status\":400,\"code\":493,\"message\":\"No mvendor found for the pvendor.\",\"developerMessage\":\"We could not find any mvendor assigned to the pVendor in database.\"},\"data\":{\"totalRespondedPO\":0,\"totalResultedPO\":0}}","options":{"uri":"http://localhost:1880/api/poList?mvendor=12345678","method":"GET","resolveWithFullResponse":true,"simple":true,"transform2xxOnly":false},"response":{"statusCode":400,"body":"{\"header\":{\"status\":400,\"code\":493,\"message\":\"No mvendor found for the pvendor.\",\"developerMessage\":\"We could not find any mvendor assigned to the pVendor in database.\"},\"data\":{\"totalRespondedPO\":0,\"totalResultedPO\":0}}","headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"220","etag":"W/\"dc-TgpjeTiW35/B8BT8qj1jFg\"","date":"Fri, 27 Jan 2017 11:11:44 GMT","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:1880","port":"1880","hostname":"localhost","hash":null,"search":"?mvendor=12345678","query":"mvendor=12345678","pathname":"/api/poList","path":"/api/poList?mvendor=12345678","href":"http://localhost:1880/api/poList?mvendor=12345678"},"method":"GET","headers":{}}}}

**Comment by chaitanya9249** [comment]
Hi Friends..
Final I got the solution.We have to override the status code 200 instead of 400(Bad Request) and keep 
    "content-type": "application/json",
    "content-length": data.toString().length

as Headers

Here is the code:

var dataMsg = msg.payload;//data from api

**msg.headers = {**
    **"content-type": "application/json",**
    **"content-length": dataMsg.toString().length**
**}**

var msgVal;
var attachments
var parseData = JSON.parse(dataMsg);
if (parseData.header.status !== 200) {  //If response 400 or any other error response
    msgVal = parseData.header.message;
    attachment._attachment.template.content[1] = msgVal.toString();
    attachments = attachment;
} 
msg.payload = attachments;
msg.statusCode = 200;
return msg;

**Comment by ptersilie** [comment]
I'm glad you found a solution to your problem. :)
