### ISSUE TITLE
How to create "live chat" by using node red with "olark" ? 

### ISSUE THREAD

**Issue by chaitanya9249** [softdevteam/mattermost-github-integration#28]
Hi
I would like to integrate live chat with a messenger by using **NODE-RED** with **olark api**.
Can any one please help me to send me the solutions.

Here is my email id : chaitu.modela99@gmail.com
Thank you.

**Comment by ptersilie** [comment]
As I mentioned before I am not familiar with node-red or olark api and I'm not sure what this has to do with this mattermost plugin. You are probably better off look for help here: http://stackoverflow.com/
