### ISSUE TITLE
any TL,DR guide for config ?

### ISSUE THREAD

**Issue by mohandeath** [softdevteam/mattermost-github-integration#49]
what is the secret_key that should I provide in the `config.py` file? is that the key GitHub provides for new OAuth applications or the other ones ? does it work for the private repositories I contribute to?
i recently migrated from slack to mattermost and new to the concept btw

**Comment by ptersilie** [comment]
It's the secret key that can be set in the Github Webhook config. I've updated the ReadMe to (hopefully) clarify this more.
