### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SERVER

### ISSUE THREAD

**Issue by etursunbaev** [softdevteam/mattermost-github-integration#50]
```
root@mmm:/mattermost-github-integration# python server.py
Traceback (most recent call last):
  File "server.py", line 7, in <module>
    host=config.SERVER['address'] or "0.0.0.0",
AttributeError: 'module' object has no attribute 'SERVER'
root@mmm:/mattermost-github-integration# 
```
Using method 1

README is not clear full

How to install and run properly this app?

```
root@mmm:/mattermost-github-integration# cat mattermostgithub/config.py
USERNAME = "Github"
ICON_URL = ""

# Repository settings
MATTERMOST_WEBHOOK_URLS = {
    'default' : ("https://my_domain.com/hooks/eimqnptb678gfrwb9w56szeaya", "room-bots"),
}

# Ignore specified event actions
GITHUB_IGNORE_ACTIONS = {
    "pull_request": ["synchronize"]
}

# Ignore events from specified users
IGNORE_USERS = {
    "someuser": ["push"],
    "anotheruser": ["push", "create"]
}

# Redirect events to different channels
REDIRECT_EVENTS = {
    "push": "commits"
}
SECRET = ""
SHOW_AVATARS = True
SERVER = {
    'hook': "/",
    'address': "0.0.0.0",
    'port': 5000,
}
```

**Comment by ptersilie** [comment]
You are right, the Readme is not entirely clear on this. The `config.py` file needs to be copied to the root folder, e.g. `mattermost-github-integration`. I will adjust the Readme accordingly.

**Comment by ptersilie** [comment]
Actually, it shouldn't matter. The config can live either in the root or in `mattermostgithub`. In your case it may be that you have another `config.py` in the root, which is missing the `SERVER` bit. So maybe just delete that, or move `mattermost-github-integration/mattermostgithub/config.py` to `mattermost-github-integration/config.py`.

**Comment by etursunbaev** [comment]
copied to root 
and seems to work now

```
root@mmm:/mattermost-github-integration# python server.py
 * Serving Flask app "mattermostgithub" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```
How to make sure it works?

I mean the mattermost part, which webhooks to use "incoming/outgoing" and etc?

**Comment by etursunbaev** [comment]
I need some good instruction how to configure in mattermost and GitHub parts.

**Comment by ptersilie** [comment]
You have to use incoming webhooks. See https://docs.mattermost.com/developer/webhooks-incoming.html for more information on this.

**Comment by etursunbaev** [comment]
seems I am close to make it work, but anyway not clear and I do smth wrong
I have 2 servers: 
Server A, running Mattermost and incoming webhook is created and using `mm.example.com` domain name
Server B, running this integration app on LXC container and using `integration.example.com` domain name. Also 80 port is proxy passed to LXC container to 5000 port


Should be used one domain name in both servers? or better use in one server?

**Comment by etursunbaev** [comment]
@ptersilie sorry man, can you help me to make it run your product.
