### ISSUE TITLE
missing support for some pull request review comments

### ISSUE THREAD

**Issue by karenetheridge** [softdevteam/mattermost-github-integration#53]
If you comment inside the pull request, on a line of code or somesuch, it comes through as the event type "pull_request_review_comment" which is supported.

But if you just put text in the box with approve, comment, and request changes, it comes through as "pull_request_review" which is not supported -- these messages are lost.

**Comment by ptersilie** [comment]
`pull_request_review` should be supported as far as I can tell (see https://github.com/softdevteam/mattermost-github-integration/blob/1124a0ff233b50ed6070cb84cfffd128ad219831/mattermostgithub/payload.py#L85). I'm not quite sure why it doesn't work for you. Do you have an example payload that doesn't work and that I can run some tests with?

**Comment by sungo** [comment]
There was an ops bobble on our end and we were running a much older version than I thought, one that predates that patch. I've verified that running master solves the issue. Sorry for the noise.
