### ISSUE TITLE
keep getting code 400 with json and with out json data from github.

### ISSUE THREAD

**Issue by ChrisFernandez** [softdevteam/mattermost-github-integration#7]
92.30.252.41 - - [19/Apr/2016 01:05:25] code 400, message Bad request syntax ('\x16\x03\x01\x00\xfa\x01\x00\x00\xf6\x03\x03W\x15\xbc\x94M;N\x9e\xe6\xc8\xdf\xb6q\xf4\x0e#\x1d\xe2H\x85\x1d4')
192.30.252.41 - - [19/Apr/2016 01:05:25] "��W��M;N���߶q�#�H�4" 400 -
192.30.252.40 - - [19/Apr/2016 01:06:27] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00\xfa\x01\x00\x00\xf6\x03\x03W\x15\xbc\xd3\xe1x\xf3^Q\xc9\x90\xcd\xf0\x0f\x0e\xa5DU'\xb4\xa0X\x8d\xac\xd0\xcdA5\x84aQ>\x00\x00D\xc0+\xc0/\xc0,\xc00\x00\x9e\x00\xa2\x00\x9f\x00\xa3\xc0#\xc0'\xc0")
192.30.252.40 - - [19/Apr/2016 01:06:27] "��W���x�^Qɐ���DU'��X����A5�aQ>D�+�/�,�0�����#�'�      ��$�(�" 400 -
192.30.252.41 - - [19/Apr/2016 01:07:20] code 400, message Bad request version ('\xc0\x13\xc0$\xc0(\xc0')
192.30.252.41 - - [19/Apr/2016 01:07:20] "��W �L�=n����I��xLҠ^_f�ȉND�+�/�,�0�����#�'�  ��$�(�" 400 -

**Comment by ptersilie** [comment]
I've never seen this before. Where are you getting this output? How does the json object look like that GitHub sends to your plugin (the one you are supposed to see)? Are you using a secret key?

**Comment by ChrisFernandez** [comment]
The output is in the server on the stdout 
:~/mattermost-plugins/mattermost-github-integration$ python server.py 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: xx-xxx-xxx
192.30.252.40 - - [19/Apr/2016 23:12:30] code 400, message Bad request version ('\xc0\x13\xc0$\xc0(\xc0')
192.30.252.40 - - [19/Apr/2016 23:12:30] "��W���^4O�9֢�2R�<�Be:�R�Z�
                                                                   D�+�/�,�0�����#�'�   ��$�(�" 400 -


and yes I'm using a secret key.
nothing comes out in the mattermost channel I told him neither

**Comment by ChrisFernandez** [comment]
ok I figure out the issue... I'm trying to use TLS, all my servers/sites are configure to only use and accept TLS connections.. and your plugin does not seem to support it.. works when I change the hook to http... unfortunately I do not like open data to move from one place to another that way, so will install again when you guys bring it up to date.  cheers.

**Comment by tomryanx** [comment]
@ChrisFernandez you could always stick eg nginx in front to handle the TLS, and have mattermost-github-integration listen on loopback only.
